### ISSUE TITLE
Blanks

### ISSUE THREAD

**Issue by gossi** [gossi/php-code-formatter#3]
More improvements to blanks:
- [ ] Preserve Newlines #4 
- [ ] Beginning and end of methods/functions/structs #5 
- [ ] Sanitizing doubly added blanks #6
- [ ] Blanks before Comments #15 
- [ ] Blanks on empty methods/functions #19
